global:
  scrape_interval: 15s # 15초마다 메트릭을 수집

scrape_configs:
  - job_name: 'tracky-consumer'
    metrics_path: '/actuator/prometheus' # Spring Boot Actuator가 메트릭을 노출하는 경로
    static_configs:
      # Docker(for Windows/Mac) 환경에서 Prometheus 컨테이너가 호스트 머신(PC)에서 실행 중인 Spring Boot 앱에 접근할 때 사용하는 주소입니다.
      - targets: ['host.docker.internal:8083']
